apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: personal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: web
          image: zhijietan97/personal-wiki:<TAG>
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
