apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: personal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - zhijie.wiki
      secretName: zhijiewiki-tls
  ingressClassName: nginx
  rules:
    - host: zhijie.wiki
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-wiki-service
                port:
                  number: 80

